name: toy_store_pos
description: نظام إدارة ومبيعات محل ألعاب الأطفال - اليمن
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # قاعدة البيانات
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3

  # التخزين الآمن
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

  # التشفير
  crypto: ^3.0.3
  uuid: ^4.2.1

  # الترجمة
  intl: any

  # إدارة الحالة
  provider: ^6.1.1

  # PDF والطباعة
  pdf: ^3.10.7
  printing: ^5.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/